### ISSUE TITLE
Optimize gifs: convert to video?

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer-docs#1]
Animated examples are much better than static images for these types of docs. However gifs are quite heavy even if you compress them well. With the same visual quality, still at 10FPS, an h264 video weighs 6-7 times less.

2-3mb to download can be a big deal on smartphones and for people who have paid data plans. We can't display videos on GitHub but as soon as we move the docs to another website it's possible to embed them and have them play like gifs.

**Comment by davcri** [comment]
Videos are simpler to record and edit and also loading times will benefit!  
So for the moment: I'll continue to use gifs on the docs, but I'll record also videos.

**Comment by davcri** [comment]
What about video resolution ? I tried Blender at 720p but the GUI elements are small without video editing (zoom-in). Maybe it's better to stick with 480p.

**Comment by NathanLovato** [comment]
480p sounds good to put inside the docs :)

**Comment by davcri** [comment]
Here they are: https://github.com/GDquest/Blender-power-sequencer-docs/tree/master/docs/video

I always uploaded them on YT (unlisted), so it's easier to view them:  https://www.youtube.com/watch?v=D3pcPG6xbTY&index=5&list=PLS5qoDcqTjGOlHy_aa2vI-MYzP4SXJvWq 

They are almost the same as the gifs, except for the `import-local-footage` that now shows also the keyboard shortcut.

**Comment by NathanLovato** [comment]
Thank you very much Davide, they're excellent! No need to bother uploading them on Youtube, at least if you don't want to show them to someone else. It's one less step. Also as we're settled on the video format etc. let's close this.

Also you don't have to add the gifs on top of the videos. It'll force me to prepare the docs setup faster :)

**Comment by davcri** [comment]
I'm glad that they are fine ;) 
I uploaded them mainly to test the doc reader experience. I was afraid about the quality loss of double re-encoding (from OBS .flv  to .mp4 and then the YouTube compression).

Have you any idea for the website ? Jekyll, sphinx ? Dedicated website or gdquest.com ?

**Comment by NathanLovato** [comment]
Ah you don’t have to worry too much about double compression. For one no need to re-encode from flv to mp4 – they’re just containers, you should be able to copy the stream (I think it’s encoded with libx264 by default, maybe nvenc if your comp supports this)

 

For the docs it’ll be on gdquest yes, powered by [hugo](https://gohugo.io/). It’s hard to find time to maintain the website already, so I don’t want another tech, especially not sphinx.
