### ISSUE TITLE
Document the main 5 features

### ISSUE THREAD

**Issue by davcri** [GDquest/Blender-power-sequencer-docs#2]
- [x] Import local footage
- [x] Render videos for the web
- [x] Add and edit crossfade
- [x] Cut and trim with the mouse
- [x] Add and clear fade

**Comment by davcri** [comment]
Working on fade-in/out

**Comment by davcri** [comment]
Done with fade-in/out.
@NathanLovato is there a video tutorial for *"Render videos for the web"* ? 

After doing the last task, I'll review the docs to check for inconsistencies.

**Comment by NathanLovato** [comment]
Thanks much! There's no tutorial, but for now it's quite limited: only works in 2.78 and only renders to Youtube. I think there's a setting for twitter though. For now it's more of a shortcut to name the exported video and set all the render settings for you. But it needs some work to be user-friendly

**Comment by NathanLovato** [comment]
Just ported it, you can download the latest master of https://github.com/GDquest/Blender-power-sequencer/ and it'll run in 2.79
There are some small improvements. You'll mainly want to look into the input mapping for the options. If you can wait a few days I can record a tut for it - although right now it's a bit limited, with only 2 render presets ^^ (the ones I use/need for gdquest ;) )

**Comment by davcri** [comment]
Working on it!

**Comment by davcri** [comment]
Closing with https://github.com/GDquest/Blender-power-sequencer-docs/commit/efddc8c1846a51b18ee20216bb4c677c38220238

If there is some problem, we can open new issues!
