### ISSUE TITLE
Can't push videos: data quota reached

### ISSUE THREAD

**Issue by davcri** [GDquest/Blender-power-sequencer-docs#3]
![schermata da 2017-12-16 20-21-59](https://user-images.githubusercontent.com/6860637/34073673-dd3be10e-e29e-11e7-8dff-86ff0c1d32d7.png)

From ["Github - About storage and bandwidth"](https://help.github.com/articles/about-storage-and-bandwidth-usage/):

> All personal and organization accounts using Git LFS receive 1 GB of free storage and 1 GB a month of free bandwidth. 

It's strange because I don't think we reached the limit of 1GB.

--- 

In the meantime I uploaded them [here](https://www.youtube.com/playlist?list=PLS5qoDcqTjGOlHy_aa2vI-MYzP4SXJvWq).

**Comment by NathanLovato** [comment]
The account did with the Godot 3 presentation. Yeah gotta remove LFS from all repos for now.

**Comment by NathanLovato** [comment]
Done, you can now add back your videos as regular git tracked files in the /video/ folder (they're small enough and we won't change them anytime soon so no need for git lfs) - and I'll keep uploading put the tutorials to Youtube.
Apparently the git lfs files stay in storage on github until you delete and re-create the repo. But well considering the size it's okay I guess.

**Comment by davcri** [comment]
Re-uploading old videos ;)
Done: https://github.com/GDquest/Blender-power-sequencer-docs/commit/3fe93cdeb34141284cc8e5f6e3f53a75dd35e604
