### ISSUE TITLE
Create Hugo templates for the documentation

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer-docs#8]
The new [GDquest website](http://gdquest.com/) is up so now it's time to add some templates to have some nicer look, and a more accessible UX than on GitHub

For now, everything from the docs/ folder in this repo should go to content/blender/power-sequencer/docs. Hugo should treat them as resource files so we can loop through them and create a side-menu and list of articles/cards.

Then there's the features list and shortcuts thanks to @doakey3, should work with [this script](https://github.com/GDquest/Blender-power-sequencer/blob/dev/utils/make_info_json.py). It should be best to have it as JSON data and have Hugo process as for the GitHub readme it's mostly hard-coded html table generation in a handful of script files

@davcri would you be interested in and have the time to give a hand here?

**Comment by davcri** [comment]
Is this issue still valid?

Currently the page [gdquest.com/blender/power-sequencer/docs/](https://www.gdquest.com/blender/power-sequencer/docs/) is generated from Hugo, correct?

**Comment by NathanLovato** [comment]
yeah I should close this repository altogether, nobody's contributing
